namespace genddl
{
    internal class DbMapping
    {

        private static readonly Dictionary<string, string> SqliteTypeMapping = new()
        {
            {"Id", "INTEGER PRIMARY KEY AUTOINCREMENT"},
            {"Text", "TEXT"},
            {"Number", "INTEGER"},
            {"Date", "DATE"},
            {"DateTime", "DATETIME"},
            {"Time", "TIME"},
            {"CheckBox", "BOOLEAN"},
            {"Link", "TEXT"},
            {"Select", "TEXT"},
            {"RadioGroup", "TEXT"}
        };

        private static readonly Dictionary<string, string> SqlserverTypeMapping = new()
        {
            {"Id", "BIGINT IDENTITY(1,1) PRIMARY KEY"},
            { "text", "NVARCHAR(MAX)"},
            { "Number", "INT"},
            { "Date", "DATE"},
            { "DateTime", "DATETIME"},
            { "Time", "TIME"},
            { "CheckBox", "BIT"},
            { "Link", "NVARCHAR(MAX)"},
            { "Select", "NVARCHAR(MAX)"},
            { "RadioGroup", "NVARCHAR(MAX)"}
        };

        private static readonly Dictionary<string, string> PostgresqlTypeMapping = new()
        {
            {"Id", "BIGSERIAL PRIMARY KEY"},
            {"text", "TEXT"},
            {"Number", "INTEGER"},
            {"Date", "DATE"},
            {"DateTime", "TIMESTAMP"},
            {"Time", "TIME"},
            {"CheckBox", "BOOLEAN"},
            {"Link", "TEXT"},
            {"Select", "TEXT"},
            {"RadioGroup", "TEXT"}
        };

        private static readonly Dictionary<string, string> OracleTypeMapping = new()
        {
            {"Id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"},
            {"text", "VARCHAR2(4000)"},
            {"Number", "NUMBER"},
            {"Date", "DATE"},
            {"DateTime", "TIMESTAMP"},
            {"Time", "TIMESTAMP WITH LOCAL TIME ZONE"},
            {"CheckBox", "NUMBER(1)"},
            {"Link", "VARCHAR2(4000)"},
            {"Select", "VARCHAR2(4000)"},
            {"RadioGroup", "VARCHAR2(4000)"}
        };

        public static string MapToColumnType(string databaseType, string fieldType)
        {
            var typeKey = fieldType.ToLower();
            return databaseType switch
            {
                "sqlite" => SqliteTypeMapping[typeKey],
                "sqlserver" => SqlserverTypeMapping[typeKey],
                "mssql" => SqlserverTypeMapping[typeKey],
                "postgresql" => PostgresqlTypeMapping[typeKey],
                "pgsql" => PostgresqlTypeMapping[typeKey],
                "oracle" => OracleTypeMapping[typeKey],
                _ => throw new Exception($"Database type not supported: {databaseType}")
            };
        }

    }
}
