//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace AccessSample.Designer.Properties
{
  /// <summary>
  ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
  /// </summary>
  // このクラスは StronglyTypedResourceBuilder クラスが ResGen
  // または Visual Studio のようなツールを使用して自動生成されました。
  // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
  // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    /// <summary>
    ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessSample.Designer.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   bi bi-123
    ///bi bi-alarm-fill
    ///bi bi-alarm
    ///bi bi-align-bottom
    ///bi bi-align-center
    ///bi bi-align-end
    ///bi bi-align-middle
    ///bi bi-align-start
    ///bi bi-align-top
    ///bi bi-alt
    ///bi bi-app-indicator
    ///bi bi-app
    ///bi bi-archive-fill
    ///bi bi-archive
    ///bi bi-arrow-90deg-down
    ///bi bi-arrow-90deg-left
    ///bi bi-arrow-90deg-right
    ///bi bi-arrow-90deg-up
    ///bi bi-arrow-bar-down
    ///bi bi-arrow-bar-left
    ///bi bi-arrow-bar-right
    ///bi bi-arrow-bar-up
    ///bi bi-arrow-clockwise
    ///bi bi-arrow-counterclockwise
    ///bi bi-arrow-down-circle-fill
    ///bi bi-arrow-do [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string bootstrap_icons
    {
      get
      {
        return ResourceManager.GetString("bootstrap_icons", resourceCulture);
      }
    }

    /// <summary>
    ///   型 System.Byte[] のローカライズされたリソースを検索します。
    /// </summary>
    internal static byte[] EmptyTemplate
    {
      get
      {
        object obj = ResourceManager.GetObject("EmptyTemplate", resourceCulture);
        return ((byte[])(obj));
      }
    }

    /// <summary>
    ///   型 System.Byte[] のローカライズされたリソースを検索します。
    /// </summary>
    internal static byte[] GettingStartedTemplate
    {
      get
      {
        object obj = ResourceManager.GetObject("GettingStartedTemplate", resourceCulture);
        return ((byte[])(obj));
      }
    }

    /// <summary>
    ///   型 System.Byte[] のローカライズされたリソースを検索します。
    /// </summary>
    internal static byte[] sqlite_sample
    {
      get
      {
        object obj = ResourceManager.GetObject("sqlite_sample", resourceCulture);
        return ((byte[])(obj));
      }
    }
  }
}
